### ISSUE TITLE
type definition error

### ISSUE THREAD

**Issue by ZKL-VOILET** [fingerprintjs/fingerprintjs#653] opened 2021-04-28 02:38 UTC
![image](https://user-images.githubusercontent.com/56717113/116338014-acad1e80-a80d-11eb-837e-8834c2ced1ef.png)

cannot find name 'top'、'right'、'bottom'、'left'
error in node_modules/@fingerprintjs/fingerprintjs/dist/fp.d.ts

**Comment by Finesse** [comment] 2021-04-28 02:43
This is a duplicate of https://github.com/fingerprintjs/fingerprintjs/issues/651. FingerprintJS supports TypeScript version 4.0 or newer. There are 2 options at the moment:

1. Update your TypeScript to version 4
2. Refuse using the TypeScript typing provided by our NPM package. In order to do it, replace `import ... from '@fingerprintjs/fingerprintjs'` with `import ... from '@fingerprintjs/fingerprintjs/dist/fp.esm'` in your `.ts` files and add the following line to a `.d.ts` file (if there is no such file, create one anywhere with any name): `declare module '@fingerprintjs/fingerprintjs/dist/fp.esm';`

**Comment by ZKL-VOILET** [comment] 2021-04-28 02:54
it's worked.thanks

**Closed** 2021-04-28 03:04 UTC
Labels: documentation

**Comment by Finesse** [comment] 2021-04-28 03:05
Which solution have you implemented?

**Comment by ZKL-VOILET** [comment] 2021-04-28 03:07
i update my typescript vertion to 4.
