### ISSUE TITLE
The identifier is the same on two different devices

### ISSUE THREAD

**Issue by ezreall** [fingerprintjs/fingerprintjs#944] opened 2023-09-13 07:19 UTC
Why is the identifier on the same device and the same chrome platform? Just change the gmail account and the identifier will change. I also get another error in one case: gest mode chrome and edge default are generated together. same identifier

**Comment by Finesse** [comment] 2023-09-16 05:19
Closed as a duplicate of https://github.com/fingerprintjs/fingerprintjs/issues/861#issuecomment-1717074162

**Closed by Finesse** 2023-09-16 05:19 UTC
