### ISSUE TITLE
Audio fingerprint timed out. Please report bug at https://github.com/fingerprintjs/fingerprintjs with your user agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15 (Applebot/0.1; +http://www.apple.com/go/applebot)".

### ISSUE THREAD

**Issue by thefinccc** [fingerprintjs/fingerprintjs#992] opened 2024-03-21 03:55 UTC
Audio fingerprint timed out. Please report bug at https://github.com/fingerprintjs/fingerprintjs with your user agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15 (Applebot/0.1; +http://www.apple.com/go/applebot)".

**Comment by JuroUhlar** [comment] 2024-03-21 13:13
Thanks for reporting! @Finesse what's the usual next step for these kinds of bug reports?

**Comment by Finesse** [comment] 2024-03-26 04:17
@JuroUhlar I don't recognize this type of bug report message. I suppose it was asked by another party. Treat is as a regular bug report.

@thefinccc Audio fingerprint times out sometimes, it's not a bug. It would be a bug if it timed out steadily in some cases. Can you provide more details?

**Comment by Finesse** [comment] 2024-03-26 10:43
We've found the bug reporting message in [FingerprintJS v2](https://github.com/fingerprintjs/fingerprintjs/blob/5db63ed6613ddc6633c5fcc7a986018ea698c2ef/fingerprint2.js#L387). That version is not supported already, and the message is not up to date, so I'm closing the issue.

**Closed by Finesse** 2024-03-26 10:43 UTC
