### ISSUE TITLE
Error: Network connection error

### ISSUE THREAD

**Issue by lintangtimur** [fingerprintjs/fingerprintjs#776] opened 2022-06-25 12:37 UTC
### Scenario

- What causes the fingerprint to change?
Using example code from homepage
- What device and browser are you using?
chrome browser windows 10
- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment)
fingerprintjs pro

### Fingerprint data
```js
import FingerprintJS from '@fingerprintjs/fingerprintjs-pro'

// Initialize an agent at application startup.
const fpPromise = FingerprintJS.load({
  apiKey: 'xxxx'
})

// Get the visitor identifier when you need it.
fpPromise
  .then(fp => fp.get())
  .then(result => console.log(result.visitorId))
```

this is the result
![image](https://user-images.githubusercontent.com/16686825/175773780-eaaeba4b-458f-438a-9aa0-97504df53a15.png)

**Comment by Finesse** [comment] 2022-06-28 05:07
Hi @lintangtimur. What browser extensions do you use? Please try to disable the extensions and try FingerprintJS again (extensions are disabled in incognito mode in Chrome by default).

**Comment by lintangtimur** [comment] 2022-06-28 16:06
tried in Incognito mode also produces the same results as the report above. The extension I use has adblock

**Comment by Valve** [comment] 2022-06-28 17:56
@lintangtimur is your ad blocker plugin enabled in incognito mode too?
If yes, that's the reason why the requests to our API are blocked.
To fix this, please implement a custom domain according to docs: https://dev.fingerprint.com/docs/subdomain-integration

**Comment by lintangtimur** [comment] 2022-06-29 00:42
Hi @Valve ,
ad blocker not running in incognito mode

**Comment by Valve** [comment] 2022-06-29 00:55
@lintangtimur I cannot reproduce this. Can you reproduce it with all your browsers? 
Please let us know the browser version, the fingerprintjs pro version that you're using.
We need a reproducible example.
The API name is resolving on my end:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/27387/176328351-98c714fd-39c8-4a89-86a5-5d3138a86ddc.png">
So I believe the issue is on your side somewhere. 
I'm going to close this issue as I see nothing wrong with the library.
If you can create a reproducible example, please feel free to reopen the issue and link to your example.
Thanks

**Closed by Valve** 2022-06-29 00:55 UTC
