### ISSUE TITLE
Uncaught Error: Mismatched anonymous define() module

### ISSUE THREAD

**Issue by mage007** [fingerprintjs/fingerprintjs#320] opened 2018-05-07 20:23 UTC
Getting the error when using this plugin with requirejs. Anybody has a fix for it? Thanks.

    Uncaught Error: Mismatched anonymous define() module: function () {
    'use strict'
    /**
     * @constructor
     * @param {Object=} options
     */

    var Fingerprint2 = function (options) {
    if (!(this instanceof Fingerprint2)) {
      return new Fingerprint2(options)
    }

    var defaultOptions = {
      swfContainerId: 'fingerprintjs2',
      swfPath: 'flash/compiled/FontList.swf',
      detectScreenOrientation: true,
      sortPluginsFor: [/palemoon/i],
      userDefinedFonts: [],
      excludeDoNotTrack: true,
      excludePixelRatio: true
    }
    this.options = this.extend(options, defaultOptions)
    this.nativeForEach = Array.prototype.forEach
    this.nativeMap = Array.prototype.map
    }

**Comment by pisaq** [comment] 2020-05-23 10:40
I've fixed it by doing this:

![Screenshot 2020-05-23 at 12 38 47 PM](https://user-images.githubusercontent.com/4266690/82728682-5e84c680-9cf2-11ea-938c-180132b8c1bc.png)

So basically it is changing first condition to the last one from `else { ... }`
Don't know if it can cause any regressions but it works fine.
Cheers.

**Comment by Valve** [comment] 2020-07-09 16:48
v3 will be implemented in TypeScript with a wide module support. Should be fixed in V3

**Comment by Finesse** [comment] 2020-09-04 12:01
@mage007 @pisaq RequireJS emits this error when a RequireJS has been run and a UMD or AMD script is running outside a RequireJS context (e.g. by a `<script>` tag). The `fingerprint2.js` script follows the UMD standard. So this error is a proper behavior of RequireJS and FingerprintJS. In version 3 we will add other formats of the scripts including IIFE that won't clash with RequireJS.

At the moment you can use one of workarounds:

1. Remove the `<script>` tag that loads FingerprintJS and wrap your `Fingerprint2` call in `require`:
    ```diff
    - <script src="your/path/to/fingerprint2.js"></script>
    <script>
    - Fingerprint2.get(...);
    + require(['your/path/to/fingerprint2.js'], (Fingerprint2) => Fingerprint2.get(...));
    </script>
    ```
- Put the FingerprintJS script tag before the RequireJS script tag:
    ```diff
    + <script src="your/path/to/fingerprint2.js"></script>
    <script src="your/path/to/require.js"></script>
    - <script src="your/path/to/fingerprint2.js"></script>
    ```
- Remove the `<script>` tag that loads FingerprintJS and put `Fingerprint2` to the global scope when it's loaded by RequireJS:
    ```js
    // After the RequireJS script and before the Fingerprint2.get call
    require(['your/path/to/fingerprint2.js'], (Fingerprint2) => {
      window.Fingerprint2 = Fingerprint2;
      // You must run you FingerprintJS code after this moment
    });
    ```
- Turn UMD into IIFE like [pisaq shown](https://github.com/fingerprintjs/fingerprintjs2/issues/320#issuecomment-633024303) if you store FingerprintJS in your VCS.

**Comment by Finesse** [comment] 2020-09-04 12:24
> fingerprintjs2 doesn't play nicely with requirejs and webpack which is a shame.

@picitujeromanov I can't reproduce a problem between Webpack and FingerprintJS. Could you please provide an example of an issue with using FingerprintJS with Webpack?

**Comment by Finesse** [comment] 2020-10-16 04:40
@mage007 @pisaq [V3](https://github.com/fingerprintjs/fingerprintjs/releases/tag/v3.0.0) is released, it's shipped in various formats including IIFE (a.k.a. global variable). This format doesn't clash with Require.js and other module loaders. Download the script from https://cdn.jsdelivr.net/npm/@fingerprintjs/fingerprintjs@3/dist/fp.min.js and see the [migration guide](https://github.com/fingerprintjs/fingerprintjs/blob/master/migrating-v2-v3.md) to learn how to migrate the rest of the code to v3.

**Closed by Finesse** 2020-10-16 04:40 UTC
Labels: enhancement

**Comment by pisaq** [comment] 2020-10-16 06:40
@Finesse We love you ! Thank you :) 
Made my day.
