### ISSUE TITLE
jsFontsKey with same values creates different Fingerprint in Safari

### ISSUE THREAD

**Issue by scysys** [fingerprintjs/fingerprintjs#528] opened 2020-06-11 09:47 UTC
### Scenario

Using the Option "{ key: 'fonts', getData: jsFontsKey, pauseBefore: true }" generates an different Fingerprint in Safari 13.

### Fingerprint data

![Bildschirmfoto 2020-06-11 um 11 42 37](https://user-images.githubusercontent.com/1695531/84371410-e6ffd400-abd9-11ea-9444-9213bb66b133.png)

**Comment by Valve** [comment] 2020-06-18 14:41
@scysys thanks for your bug report! I'm going to get back to you on this (but cannot promise a prompt response).

**Comment by Finesse** [comment] 2020-09-07 11:55
I can reproduce this bug on my MacBook. Safari has access to more fonts than other other browsers. In my case the extra fonts are: American Typewriter Condensed, Microsoft JhengHei, Roman and SimSun. Also these fonts are unlisted in the Font Book application.

FingerprintJS doesn't guarantee consistent fingerprint between browsers. The font component is marked as _almost_ browser independent in [the wiki](https://github.com/fingerprintjs/fingerprintjs2/wiki/Browser-independent-components). We can research this font behavior of Safari but this is a low priority.

**Comment by Finesse** [comment] 2020-09-07 11:56
I can reproduce this bug on my MacBook. Safari has access to more fonts than other other browsers. In my case the extra fonts are: American Typewriter Condensed, Microsoft JhengHei, Roman and SimSun. Also these fonts are unlisted in the Font Book application. @scysys, what are the extra fonts in your case?

FingerprintJS doesn't guarantee consistent fingerprint between browsers. The font component is marked as _almost_ browser independent in [the wiki](https://github.com/fingerprintjs/fingerprintjs2/wiki/Browser-independent-components). We can research this font behavior of Safari but this is a low priority.

**Comment by Valve** [comment] 2020-09-07 16:27
@scysys can you please provide more info? We don't currently understand what's broken in your case. 
> with same values creates different Fingerprint in Safari

Please provide more info about different fingerprints. Are they different in the same browser or between different browsers? Or something else, please let us know.

**Comment by Finesse** [comment] 2020-09-08 00:03
@Valve As far as I understand, Sven says that they considers the font component to be browser independent and the component gives different result in Safari. If I'm right then this is not a bug and maybe not even an enhancement to consider because the goal of FingerprintJS is to identify browsers, not devices.

**Comment by Valve** [comment] 2020-09-08 13:30
@Finesse if that's the case, then it's not a bug. We're not a font-detection library, we're a browser fingerprinting library, font lists can be browser-dependent, like you said. Unless we hear from @scysys in 7 days, please close the ticket.

**Closed** 2020-09-14 22:54 UTC
Labels: enhancement, needinfo
