### ISSUE TITLE
My available screen resolution keeps changing and as a result changes my fingerprint

### ISSUE THREAD

**Issue by swilliams-a3digital** [fingerprintjs/fingerprintjs#634] opened 2021-03-26 00:08 UTC
### I expect my fingerprint to remain the same when I am on the same device
My available screen resolution value changes by a few pixels throughout the day and it leads to my fingerprint constantly changing, making it useless.

### Fingerprint data

Time | msg.lumin.data.deviceFingerprint | msg.lumin.data.deviceComponents.availableScreenResolution.value
-- | -- | --
  | Mar 25, 2021 @ 16:48:49.518 | 5227afcc3c907c61333f12eaf471aca7 | 1792, 1017

  | Mar 25, 2021 @ 16:48:19.856 | 5227afcc3c907c61333f12eaf471aca7 | 1792, 1017

  | Mar 25, 2021 @ 16:14:53.264 | 5227afcc3c907c61333f12eaf471aca7 | 1792, 1017

  | Mar 25, 2021 @ 16:12:37.899 | 5227afcc3c907c61333f12eaf471aca7 | 1792, 1017

  | Mar 25, 2021 @ 14:17:53.904 | 5227afcc3c907c61333f12eaf471aca7 | 1792, 1017

  | Mar 25, 2021 @ 13:38:59.670 | 5227afcc3c907c61333f12eaf471aca7 | 1792, 1017

  | Mar 25, 2021 @ 13:37:32.930 | 5227afcc3c907c61333f12eaf471aca7 | 1792, 1017

  | Mar 25, 2021 @ 12:59:46.759 | 38ee242a0326f027470c3d6e4a6a86b0 | 1792, 1026

  | Mar 25, 2021 @ 12:58:24.077 | 38ee242a0326f027470c3d6e4a6a86b0 | 1792, 1026

  | Mar 25, 2021 @ 12:56:58.671 | 38ee242a0326f027470c3d6e4a6a86b0 | 1792, 1026

  | Mar 25, 2021 @ 11:57:20.677 | d16facefbbc1761aace88d642122d541 | 1792, 1028

  | Mar 25, 2021 @ 11:56:14.597 | d16facefbbc1761aace88d642122d541 | 1792, 1028

  | Mar 25, 2021 @ 11:03:47.410 | a5fe6fb71f975e2cea1001330229f52c | 1792, 1022

  | Mar 25, 2021 @ 09:08:48.161 | a5fe6fb71f975e2cea1001330229f52c | 1792, 1022

Provide the FULL DATA of both/all fingerprints using this page: https://fingerprintjs.github.io/fingerprintjs/.
Alternatively, provide a JSFiddle that reproduces the bug.

**Comment by Finesse** [comment] 2021-03-26 00:52
It's a duplicate of https://github.com/fingerprintjs/fingerprintjs/issues/568, you can find much information regarding this issue there. It will be mitigated in v3.1.0 which is going to be published in a couple weeks. Unfortunately, we don't know a way to make it 100% stable yet.

You can also [exclude this component from the fingerprint hash](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/migrating_v2_v3.md#customization).

**Closed by Finesse** 2021-03-26 00:52 UTC
