### ISSUE TITLE
Unstable 'canvas' entropy source when runs in a cross-origin iframe

### ISSUE THREAD

**Issue by tvvocold** [fingerprintjs/fingerprintjs#903] opened 2023-05-12 09:37 UTC
### Scenario

- What causes the fingerprint to change?
> canvas entropy
- What device and browser are you using?
> MacBook Air (M2) with macOS 13.3.1 (a), Safari 16.4
- What version of FingerprintJS are you using? 
> v3.4.1

### Fingerprint data
Steps to reproduce: Create two local static sites with the same fingerprintjs code, load one of them into the second site as an iframe, and then check the console logs of the latter, like this: https://gist.github.com/tvvocold/97c968d35247e5184959367baf17fc98

Logs diff:  https://www.diffchecker.com/EikNC00o/

**Comment by Finesse** [comment] 2023-05-12 09:59
@tvvocold Thank you for the detailed issued report, especially the code and the logs diff. But unfortunately I can't reproduce it. Could you please provide more details:

1. Does it always happen on your device?
2. Do the top page and the iframe use different origins? Are they HTTP, HTTPS or localhost?

Anyway, canvas is known to be unstable, and there is nothing we can really do about it. If you want more stability, you can [exclude](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/extending.md) one or both canvas images, which will also reduce the selectivity. Interestingly, the geometry canvas is more stable, but you've got it different.

**Comment by tvvocold** [comment] 2023-05-12 10:03
@Finesse 
1. Does it always happen on your device?
> Yes, always, even I had restart the Safari and clear the cache.

2. Do the top page and the iframe use different origins? Are they HTTP, HTTPS or localhost?
They are both served with HTTPS, SSL signed by [Valet](https://laravel.com/docs/10.x/valet#securing-sites)

**Comment by Finesse** [comment] 2023-05-12 10:05
Are the top page and the iframe served from the same [origin](https://developer.mozilla.org/en-US/docs/Glossary/Origin)?

**Comment by Finesse** [comment] 2023-05-12 10:06
Does the problem occur when you follow [these steps](https://github.com/fingerprintjs/fingerprintjs/discussions/765#discussioncomment-2692848)?

**Comment by tvvocold** [comment] 2023-05-12 10:07
> Are the top page and the iframe served from the same [origin](https://developer.mozilla.org/en-US/docs/Glossary/Origin)?

Nope. Different origin: _finger1.test_ and  _finger2.test_

**Comment by tvvocold** [comment] 2023-05-12 10:18
Weird, it's OK now, might be the cache issue, thx, and I will let you know(and reopen this issue) if there are diff again.

**Comment by tvvocold** [comment] 2023-05-16 08:34
@Finesse Just saw this bug again, but I don't know how to reproduce it
The log is here: https://www.diffchecker.com/Rfs3Ll6W  
and the code is the same as before: https://gist.github.com/tvvocold/97c968d35247e5184959367baf17fc98

**Comment by Finesse** [comment] 2023-05-16 12:01
Does the problem occur when you follow [these steps](https://github.com/fingerprintjs/fingerprintjs/discussions/765#discussioncomment-2692848)?

**Comment by tvvocold** [comment] 2023-05-21 07:11
> these steps


> Does the problem occur when you follow [these steps](https://github.com/fingerprintjs/fingerprintjs/discussions/765#discussioncomment-2692848)?

Nope.

**Comment by Finesse** [comment] 2023-05-22 01:33
Thanks for trying. Anyway, I'm closing this issue as a duplicate of https://github.com/fingerprintjs/fingerprintjs/issues/768. There is nothing we can do with it now, sorry.

**Closed by Finesse** 2023-05-22 01:33 UTC
Labels: needinfo
